# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c08ec81c6870d2e1d9e043c5e4f5f1e77719187fadac4b00612d057700c0e6ab3286b1c3b9facf41efcddddcd6abd81a44db289862fbcf3069acbc57e13af60e
  aws_access_key_id: AKIAJW5ORCVB537BGJZA
  aws_secret_access_key: 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

test:
  secret_key_base: ace8ff854273e03c0c488a2a642078d2cb211a46c07088ac83d102d9835ef6fa6a2f6c7e5c7a509878482da42c02af0bc74888540181253f115d6b9917a9beb6
  aws_access_key_id: AKIAJW5ORCVB537BGJZA
  aws_secret_access_key: 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

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 9f3a11c1519a16d11ed1dc860d5479ad2849b517590c9601f40e0f9e1e881b4c422066ea690928de29249c462f5f55a434f395be602cf29288c03c1ff49a60db
  aws_access_key_id: AKIAJW5ORCVB537BGJZA
  aws_secret_access_key: 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